In [1]:
import statistics 
import json
import pandas as pd
import numpy as np
import scipy.stats
from apyori import apriori
import re
import matplotlib.pyplot as plt
import powerlaw

In [2]:
df = pd.read_csv("./data/cleaned_m1_data.csv")

In [5]:
avgBotPre = df['02_ZHVI_Bot'].mean()
avgBotPost = df['08_ZHVI_Bot'].mean() 

casesPre = df['02_Cases'].mean()
casesPost = df['08_Cases'].mean()

cheaperHigh = len(df[(df['02_ZHVI_Bot']<=avgBotPre)&(df['02_Cases']>casesPre)])
cheaperLow = len(df[(df['02_ZHVI_Bot']<=avgBotPre)&(df['02_Cases']<=casesPre)])
expHigh = len(df[(df['02_ZHVI_Bot']>avgBotPre)&(df['02_Cases']>casesPre)])
expLow = len(df[(df['02_ZHVI_Bot']>avgBotPre)&(df['02_Cases']<=casesPre)])

#pre covid chi-squares
table = [[cheaperHigh, cheaperLow], [expHigh, expLow]]
scipy.stats.chi2_contingency(table)

(37.43403348191125,
 9.4557621203801e-10,
 1,
 array([[  14.18207381, 1819.81792619],
        [   7.81792619, 1003.18207381]]))

In [6]:
cheaperHigh = len(df[(df['08_ZHVI_Bot']<=avgBotPost)&(df['08_Cases']>casesPost)])
cheaperLow = len(df[(df['08_ZHVI_Bot']<=avgBotPost)&(df['08_Cases']<=casesPost)])
expHigh = len(df[(df['08_ZHVI_Bot']>avgBotPost)&(df['08_Cases']>casesPost)])
expLow = len(df[(df['08_ZHVI_Bot']>avgBotPost)&(df['08_Cases']<=casesPost)])

#post covid chi-squares
table = [[cheaperHigh, cheaperLow], [expHigh, expLow]]
scipy.stats.chi2_contingency(table)

(319.2346739678735,
 2.1262113582881006e-71,
 1,
 array([[ 295.72478032, 1545.27521968],
        [ 161.27521968,  842.72478032]]))

In [7]:
avgTopPre = df['02_ZHVI_Top'].mean()
avgTopPost = df['08_ZHVI_Top'].mean()

casesPre = df['02_Cases'].mean()
casesPost = df['08_Cases'].mean()

cheaperHigh = len(df[(df['02_ZHVI_Top']<=avgTopPre)&(df['02_Cases']>casesPre)])
cheaperLow = len(df[(df['02_ZHVI_Top']<=avgTopPre)&(df['02_Cases']<=casesPre)])
expHigh = len(df[(df['02_ZHVI_Top']>avgTopPre)&(df['02_Cases']>casesPre)])
expLow = len(df[(df['02_ZHVI_Top']>avgTopPre)&(df['02_Cases']<=casesPre)])

#pre covid chi-squares
table = [[cheaperHigh, cheaperLow], [expHigh, expLow]]
scipy.stats.chi2_contingency(table)

(40.33879985663838,
 2.1352601912598707e-10,
 1,
 array([[  14.54551845, 1866.45448155],
        [   7.45448155,  956.54551845]]))

In [9]:
cheaperHigh = len(df[(df['08_ZHVI_Top']<=avgTopPost)&(df['08_Cases']>casesPost)])
cheaperLow = len(df[(df['08_ZHVI_Top']<=avgTopPost)&(df['08_Cases']<=casesPost)])
expHigh = len(df[(df['08_ZHVI_Top']>avgTopPost)&(df['08_Cases']>casesPost)])
expLow = len(df[(df['08_ZHVI_Top']>avgTopPost)&(df['08_Cases']<=casesPost)])

#pre covid chi-squares
table = [[cheaperHigh, cheaperLow], [expHigh, expLow]]
scipy.stats.chi2_contingency(table)

(264.1268782331765,
 2.162628431770693e-59,
 1,
 array([[ 301.34692443, 1574.65307557],
        [ 155.65307557,  813.34692443]]))